config/routes.rb
Rails.application.routes.draw do
  root 'blog#home'

  get 'password_resets/new'
  post 'password_resets/create' => 'password_resets#create', as: 'create_password_reset'
  get 'password_resets/edit' => 'password_resets#edit', as: 'password_reset'
  patch 'password_resets/update' => 'password_resets#update', as: 'password_update'

  get 'sessions/new'

  get 'cabins/details' => 'details#index'
  get 'cabins/map' => 'map#index'

  get 'details' => 'details#index', as: 'details'
  get 'map' => 'map#index', as: 'map'

  get 'home' => 'blog#home', as: 'home'
  get 'rules' => 'blog#rules', as: 'rules'
  get 'faq' => 'blog#faq', as: 'faq'

  get 'accommodations' => 'accommodations#index', as: 'accommodations'
  get 'accommodations/:id' => 'accommodations#show', as: 'accommodation'
  patch 'accommodations/:id' => 'accommodations#update'

  post 'quantity/:accommodation_id' => 'reservations#quantity', as: 'quantity'
  post 'confirmation/:accommodation_id' => 'reservations#confirmation', as: 'confirmation'
  get 'reservations/:id' => 'reservations#show', as: 'edit_reservation'
  patch 'reservations/:id' => 'reservations#add_note', as: 'reservation_note'
  put 'reservations/:id/cancel' => 'reservations#cancel'
  get 'reservations' => 'reservations#index', as: 'admin_reservations'
  get 'reservations/:id/payment' => 'reservations#payment', as: 'admin_reservation_payment'
  delete 'reservations/:id' => 'reservations#delete', as: 'admin_reservation_delete'
  patch 'reservations/:id/paid' => 'reservations#paid', as: 'admin_reservation_paid'

  get 'users/new', as: 'signup'
  post 'users' => 'users#create'

  get    'login'   => 'sessions#new', as: 'login'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy', as: 'logout'

  get 'admin/index', as: 'admin'

  get 'admin/posts/home' => 'posts#show_home', as: 'admin_home'
  get 'admin/posts/rules' => 'posts#show_rule', as: 'admin_rule'
  get 'admin/posts/faq' => 'posts#show_faq', as: 'admin_faq'

  get 'admin/posts/home/new' => 'posts#new_home', as: 'new_home'
  get 'admin/posts/rules/new' => 'posts#new_rule', as: 'new_rule'
  get 'admin/posts/faq/new' => 'posts#new_faq', as: 'new_faq'

  post 'admin/posts' => 'posts#create', as: 'posts'

  get 'admin/posts/:id' => 'posts#show', as: 'edit_post'
  patch 'admin/posts/:id' => 'posts#update', as: 'post'
  patch 'admin/posts/:id/up' => 'posts#display_up', as: 'post_up'
  patch 'admin/posts/:id/down' => 'posts#display_down', as: 'post_down'
  delete 'admin/posts/:id' => 'posts#delete', as: 'delete_post'

  get 'admin/registrations' => 'registrations#index', as: 'registrations'
  get 'users/:id' => 'users#show', as: 'user'
  get 'users/:id/reservations' => 'users#reservations', as: 'user_reservations'
  patch 'users/:id' => 'users#update'
  patch 'users/:id/tier_approved' => 'users#tier_approved', as: 'tier_approved'

  get 'admin/buildings' => 'buildings#index', as: 'buildings'
  get 'admin/buildings/:id' => 'buildings#show', as: 'building'
  patch 'admin/buildings/:id' => 'buildings#update'

  get 'tiers' => 'tiers#index'
  get 'tiers/:id' => 'tiers#show', as: 'tier_edit'
  patch'tiers/:id' => 'tiers#update', as: 'tier'
  patch 'tiers/:id/tier_open_confirmation' => 'tiers#tier_open_email_confirm', as: 'tier_open_confirm'
  patch 'tiers/:id/send_open_confirmation' => 'tiers#tier_open_email_send', as: 'tier_open_send'
  get 'tiers/:id/email_logs' => 'email_logs#tier_email_logs', as: 'tier_email_logs'

  get 'instants' => 'instants#index'
  get 'instants/:id' => 'instants#show', as: 'instant_edit'
  patch'instants/:id' => 'instants#update', as: 'instant_update'
end

app/models/tier.rb
class Tier 
  include Mongoid::Document

  has_many :users

  before_save :strip_whitespace

  validates :label, presence: true, length: { maximum: 40 }
  validates :description, presence: true, length: { maximum: 255 }
  validates :subject, presence: true, length: { maximum: 255 }
  validates :email_text, presence: true
  validates :email_html, presence: true

  def full_label
    "#{label}: #{description}"
  end

  private

  def strip_whitespace
    self.label = self.label.strip unless self.label.nil?
    self.description = self.description.strip unless self.description.nil?
    self.subject = self.subject.strip unless self.subject.nil?
    self.email_text = self.email_text.strip unless self.email_text.nil?
    self.email_html = self.email_html.strip unless self.email_html.nil?
  end
end

app/controllers/tiers_controller.rb
class TiersController < ApplicationController
  before_action :require_admin

  def index
    @tiers = Tier.all()
  end

  def show
    @tier = Tier.find(params[:id])
    @error = @tier
  end

  def update
    @tier = Tier.find(params[:id])
    @error = @tier # tell _error_messages.html.erb to use this object for form errors

    if @tier.update(tier_params)
      logger.info("user #{current_user.id} updated tier #{@tier.id}")
      flash[:success] = 'tier updated'
      index
      redirect_to tiers_path
    else
      render 'show'
    end
  end

  def tier_open_email_confirm
    @tier = Tier.find(params[:id])
    @error = @tier

    if !@tier.valid?
      flash.now[:warning] = "Tier is invalid, please edit first"
      render 'show'
    end
  end

  def tier_open_email_send
    logger.info("user #{current_user.id} sending open email")
    @tier = Tier.find(params[:id])
    @error = @tier

    UserMailer.tier_open_email(@tier, @tier.users.map {|u| u.email}).deliver_now
    @tier.users.each {|u| EmailLog.create(email_type: 'tier_open_email', user: u, tier: @tier)}

    flash[:success] = "tier opening email sent for #{@tier.description} tier."
    index
    @tier.sent_date = Time.new
    @tier.save
    redirect_to tiers_path
  end

  private

  def tier_params
    params.require(:tier).permit(:label, :description, :available, :email_text, :email_html, :subject)
  end
end

app/helpers/tiers_helper.rb
module TiersHelper
  def tier_count(t)
    return User.where(tier: t.id).count
  end

  def duration(difference)
    ActiveSupport::Duration
      .build(difference)
      .parts
      .except(:seconds)
      .reduce('') { |output, (key, val)| output += "#{val}#{key.to_s.first} " }
      .strip
  end
end

app/views/tiers/index.html.erb
<div class="row pt-3">
  <div class="col">
    <h3>tier management</h3>
  </div>
</div>

<% i = 0; @tiers.each do |t| %>
  <% if i % 2 == 0 %>
    <div class="row">
  <% end %>
  <div class="col-6 p-1">
    <div class="border rounded bg-light">
      <div class="text-light bg-dark rounded-top p-2 text-center"><%= "#{t.label}: #{t.description}" %></div>
      <div class="row" title="Time from now: <%= duration(t.available - Time.new) %>">
        <div class="col-md-3 text-md-right">Tier Open:</div>
        <div class="col-md-auto text-value"><%= t.available.strftime("%a %-d %b %Y %T %Z") %></div>
      </div>
      <div class="row">
        <div class="col-md-3 text-md-right">Sent:</div>
        <div class="col-auto text-value"><%= t.sent_date ? t.sent_date.strftime("%a %-d %b %Y %T %Z") : '[nope]' %></div>
      </div>
      <div class="row">
        <div class="col-md-3 text-md-right">Friends:</div>
        <div class="col-auto text-value"><%= tier_count(t) %></div>
      </div>
      <div class="row text-center m-4">
        <div class="col">
          <%= link_to tier_edit_path(t) do %>
            <button type="button" class="btn btn-info w-100" >Edit Tier</button>
          <% end %>
        </div>
      </div>
      <% if !t.sent_date %>
        <div class="row text-center m-4">
          <div class="col">
            <%= link_to tier_open_confirm_path(t), :method => :patch do %>
              <button type="button" class="btn btn-info w-100">Send Tier Opening Email</button>
            <% end %>
          </div>
        </div>
      <% else %>
        <div class="row text-center m-4">
          <div class="col">
            <%= link_to tier_email_logs_path(t.id) do %>
              <button type="button" class="btn btn-info w-100">View Email Logs</button>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <% if i % 2 == 1 %>
    </div>
  <% end %>
  <% i += 1 %>
<% end %>

app/views/tiers/show.html.erb
<div class="row justify-content-md-center">
  <div class="col-md-10">
    <%= form_for(@tier) do |f| %>
      <%= render 'layouts/error_messages' %>
      <div class="field">
        <%= f.label :label %><br>
        <%= f.text_field :label, :maxlength => 40 %>
      </div>
      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_field :description, :maxlength => 255 %>
      </div>
      <div class="field date">
        <%= f.label :available %>
        <%= f.datetime_select :available %> UTC
      </div>
      <div class="field">
        <%= f.label :subject %>
        <%= f.text_field :subject%>
      </div>
      <div class="field">
        <%= f.label :email_text %>
        <%= f.text_area :email_text %>
      </div>
      <div class="field">
        <%= f.label :email_html %>
        <%= f.text_area :email_html, :class => 'tinymce' %>
      </div>
      <div class="actions">
        <%= f.submit "Update", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>
<%= tinymce %>

app/views/tiers/tier_open_email_confirm.html.erb
<div class="row pt-3 mx-auto">
  <div class="status alert-danger">
    <strong>Please confirm</strong>
    <div>
      You have requested to send an email from the `cabins@fnf.org` email account to all of the users in
      the <%= @tier.description %> tier. In order to do this, please confirm the following information and hit send.
    </div>
  </div>
</div>

<div class="row justify-content-md-center">
  <div class="col-md-10">
    Subject:
    <div class="border rounded bg-light m-2 p-2">
      <%= @tier.subject %>
    </div>
    Text version of the email:
    <div class="border rounded bg-light m-2 p-2">
      <%= @tier.email_text %>
    </div>
    HTML version of the email:
    <div class="border rounded bg-light m-2 p-2">
      <%= @tier.email_html.try(:html_safe) %>
    </div>
    <div>There are <%= tier_count(@tier) %> Friends & Family members in this tier. They are...</div>
    <div class="border rounded bg-light m-2 p-2">
      <% @tier.users.each do |u| %>
        <div class="row">
          <div class="col-sm-3 text-sm-right">
            <%= u.name %>
          </div>
          <div class="col-sm-9 col-sm-">
            <%= u.email %>
          </div>
        </div>
      <% end %>
    </div>
    <h3 class="mt-4">Are you really wanting to send this email to them? If so, answer the following question and hit
      send</h3>
    <%
      number1 = (rand * 100).round(0)
      number2 = (rand * 100).round(0)
    %>
    <input type="hidden" id="number1" value="<%= number1 %>"/>
    <input type="hidden" id="number2" value="<%= number2 %>"/>
    <%= form_for @tier, :url => tier_open_send_path do |f| %>
      <%= render 'layouts/error_messages' %>
      <%= f.hidden_field :id %>
      <div class="field">
        <label for="answer"><%= "What is #{number1} + #{number2}?" %></label>
        <input type="text" id="answer"/>
      </div>
      <div class="actions">
        <%= f.submit "Send", name: 'tier_email_send', class: 'btn btn-primary' %>
        <%= link_to tiers_path do %>
          <button type="button" class="btn btn-primary">Cancel</button>
        <% end %>
        <div class="mb-4" style="font-size: 80%">
          *By clicking this button, you agree that you have not had any more than two (2) whiskeys and that you
          understand the consequences of this action. If you would like me to talk to you through it, please bring me a
          bottle of whiskey.
        </div>
      </div>
    <% end %>
  </div>
</div>