config/routes.rb
Rails.application.routes.draw do
  root 'blog#home'

  get 'password_resets/new'
  post 'password_resets/create' => 'password_resets#create', as: 'create_password_reset'
  get 'password_resets/edit' => 'password_resets#edit', as: 'password_reset'
  patch 'password_resets/update' => 'password_resets#update', as: 'password_update'

  get 'sessions/new'

  get 'cabins/details' => 'details#index'
  get 'cabins/map' => 'map#index'

  get 'details' => 'details#index', as: 'details'
  get 'map' => 'map#index', as: 'map'

  get 'home' => 'blog#home', as: 'home'
  get 'rules' => 'blog#rules', as: 'rules'
  get 'faq' => 'blog#faq', as: 'faq'

  get 'accommodations' => 'accommodations#index', as: 'accommodations'
  get 'accommodations/:id' => 'accommodations#show', as: 'accommodation'
  patch 'accommodations/:id' => 'accommodations#update'

  post 'quantity/:accommodation_id' => 'reservations#quantity', as: 'quantity'
  post 'confirmation/:accommodation_id' => 'reservations#confirmation', as: 'confirmation'
  get 'reservations/:id' => 'reservations#show', as: 'edit_reservation'
  patch 'reservations/:id' => 'reservations#add_note', as: 'reservation_note'
  put 'reservations/:id/cancel' => 'reservations#cancel'
  get 'reservations' => 'reservations#index', as: 'admin_reservations'
  get 'reservations/:id/payment' => 'reservations#payment', as: 'admin_reservation_payment'
  delete 'reservations/:id' => 'reservations#delete', as: 'admin_reservation_delete'
  patch 'reservations/:id/paid' => 'reservations#paid', as: 'admin_reservation_paid'

  get 'users/new', as: 'signup'
  post 'users' => 'users#create'

  get    'login'   => 'sessions#new', as: 'login'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy', as: 'logout'

  get 'admin/index', as: 'admin'

  get 'admin/posts/home' => 'posts#show_home', as: 'admin_home'
  get 'admin/posts/rules' => 'posts#show_rule', as: 'admin_rule'
  get 'admin/posts/faq' => 'posts#show_faq', as: 'admin_faq'

  get 'admin/posts/home/new' => 'posts#new_home', as: 'new_home'
  get 'admin/posts/rules/new' => 'posts#new_rule', as: 'new_rule'
  get 'admin/posts/faq/new' => 'posts#new_faq', as: 'new_faq'

  post 'admin/posts' => 'posts#create', as: 'posts'

  get 'admin/posts/:id' => 'posts#show', as: 'edit_post'
  patch 'admin/posts/:id' => 'posts#update', as: 'post'
  patch 'admin/posts/:id/up' => 'posts#display_up', as: 'post_up'
  patch 'admin/posts/:id/down' => 'posts#display_down', as: 'post_down'
  delete 'admin/posts/:id' => 'posts#delete', as: 'delete_post'

  get 'admin/registrations' => 'registrations#index', as: 'registrations'
  get 'users/:id' => 'users#show', as: 'user'
  get 'users/:id/reservations' => 'users#reservations', as: 'user_reservations'
  patch 'users/:id' => 'users#update'
  patch 'users/:id/tier_approved' => 'users#tier_approved', as: 'tier_approved'

  get 'admin/buildings' => 'buildings#index', as: 'buildings'
  get 'admin/buildings/:id' => 'buildings#show', as: 'building'
  patch 'admin/buildings/:id' => 'buildings#update'

  get 'tiers' => 'tiers#index'
  get 'tiers/:id' => 'tiers#show', as: 'tier_edit'
  patch'tiers/:id' => 'tiers#update', as: 'tier'
  patch 'tiers/:id/tier_open_confirmation' => 'tiers#tier_open_email_confirm', as: 'tier_open_confirm'
  patch 'tiers/:id/send_open_confirmation' => 'tiers#tier_open_email_send', as: 'tier_open_send'
  get 'tiers/:id/email_logs' => 'email_logs#tier_email_logs', as: 'tier_email_logs'

  get 'instants' => 'instants#index'
  get 'instants/:id' => 'instants#show', as: 'instant_edit'
  patch'instants/:id' => 'instants#update', as: 'instant_update'
end

app/models/post.rb
class Post
  include Mongoid::Document

  @allowed_categories = %w(home rule faq)

  validates :category, presence: true, length: { maximum: 40 }, :inclusion => { :in => @allowed_categories }
  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_admin

  def show_posts
    @posts = Post.where(category: @category).order(display_order: :asc, id: :asc)
    @path = Rails.application.routes.url_helpers.send("new_#{@category}_path")
    render 'posts/index'
  end

  def show_home
    @category = 'home'
    show_posts
  end

  def show_rule
    @category = 'rule'
    show_posts
  end

  def show_faq
    @category = 'faq'
    show_posts
  end

  def new
    @post = Post.new
    @post.category = @category
    @error = @post # tell _error_messages.html.erb to use this object for form errors
    render 'posts/new'
  end

  def new_home
    @category = 'home'
    new
  end

  def new_rule
    @category = 'rule'
    new
  end

  def new_faq
    @category = 'faq'
    new
  end

  def create
    @post = Post.new(post_params)
    @category = @post.category
    @error = @post # tell _error_messages.html.erb to use this object for form errors

    if @post.save
      logger.info("user #{current_user.id} created post #{@post.id} in category #{@category}")
      flash.now[:success] = "#{@category} post created!"
      show_posts
    else
      new
    end
  end

  def show
    @post = Post.find(params[:id])
    @error = @post
  end

  def update
    @post = Post.find(params[:id])
    @category = @post.category
    @error = @post # tell _error_messages.html.erb to use this object for form errors

    if @post.update(post_params)
      logger.info("user #{current_user.id} updated post #{@post.id} in category #{@category}")
      flash.now[:success] = 'post updated'
      show_posts
    else
      render 'show'
    end
  end

  # up is down & down is up
  def display_up
    display_delta(-1)
  end

  # up is down & down is up
  def display_down
    display_delta(1)
  end

  def display_delta(inc)
    @post = Post.find(params[:id])
    @category = @post.category
    @display_order = @post.display_order
    @error = @post # tell _error_messages.html.erb to use this object for form errors

    if @post.display_order
      @post.display_order += inc
    else
      @post.display_order = 50
    end

    @post.save
    if @post.save
      # flash.now[:success] = "display order updated"
    else
      flash.now[:danger] = @post.errors.full_messages
    end
    show_posts
  end

  def delete
    @post = Post.find(params[:id])
    @category = @post.category
    @post.destroy
    logger.info("user #{current_user.id} deleted post #{@post.id} in category #{@category}")
    flash.now[:success] = "post deleted"
    show_posts
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :category, :display_order)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<div class="titlewrapper mt-3">
  <div class="admintitle"><h3><%= @category %> post management</h3></div>
  <div class="right"><h4><%= link_to 'new', @path, class: 'green' %></h4></div>
</div>
<table class="table table-hover table-condensed admintable">
  <thead>
  <tr>
    <th>
      ID
    </th>
    <th>
      Title
    </th>
    <th>
      Body
    </th>
    <th>
      Order
    </th>
    <th>
      Actions
    </th>
  </tr>
  </thead>
  <tbody>
  <% @posts.each do |p| %>
    <tr data-item-id=<%= "#{p.id}" %> class="item">
      <td>
        <%= p.id %>
      </td>
      <td>
        <%= p.title.try(:html_safe) %>
      </td>
      <td>
        <%= p.body.try(:html_safe) %>
      </td>
      <td title="current order: <%= p.display_order %> (sorted top to bottom, lowest to highest)">
        <%= link_to post_up_path(p), :method => :patch do %><%= octicon "triangle-up", :height => 32, :class => "right left", :"aria-label" => "up" %><% end %>
        <%= link_to post_down_path(p), :method => :patch do %><%= octicon "triangle-down", :height => 32, :class => "right left", :"aria-label" => "down" %><% end %>
      </td>
      <td>
        <%= link_to 'edit', post_path(p) %>
        <%= link_to 'delete', p, method: :delete, data: {confirm: 'Are you sure you want to delete this post?'} %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<div class="row">
  <h3>Creating a new <%= @category %> post</h3>
</div>
<div class="row justify-content-md-center">
  <div class="col-md-10">
    <%= form_for(@post) do |f| %>
        <%= render 'layouts/error_messages' %>
        <%= hidden_field(:post, :category) %>
      <div class="field">
        <%= f.label :title %><br>
        <%= f.text_area :title, :class => 'tinymce' %>
      </div>
      <div class="field">
        <%= f.label :body %><br>
        <%= f.text_area :body, class: 'tinymce' %>
      </div>
      <div class="field">
        <%= f.label :display_order, class: 'same-line' %>
        <%= f.number_field :display_order, :value => 50%>
        sorted from top to bottom, lowest to highest
      </div>
      <div class="actions">
        <%= f.submit "Create", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>
<%= tinymce %>

app/views/posts/show.html.erb
<div class="row justify-content-md-center">
  <div class="col-md-10">
    <%= form_for(@post) do |f| %>
        <%= render 'layouts/error_messages' %>
        <%= hidden_field(:post, :category) %>
      <div class="field">
        <%= f.label :title %><br>
        <%= f.text_area :title, :class => 'tinymce' %>
      </div>
      <div class="field">
        <%= f.label :body %><br>
        <%= f.text_area :body, :class => 'tinymce' %>
      </div>
        <div class="field">
          <%= f.label :display_order, class: 'same-line' %>
          <%= f.number_field :display_order %>
          sorted from top to bottom, lowest to highest
        </div>
      <div class="actions">
        <%= f.submit "Update", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>
<%= tinymce %>