config/routes.rb
Rails.application.routes.draw do
  root 'blog#home'

  get 'password_resets/new'
  post 'password_resets/create' => 'password_resets#create', as: 'create_password_reset'
  get 'password_resets/edit' => 'password_resets#edit', as: 'password_reset'
  patch 'password_resets/update' => 'password_resets#update', as: 'password_update'

  get 'sessions/new'

  get 'cabins/details' => 'details#index'
  get 'cabins/map' => 'map#index'

  get 'details' => 'details#index', as: 'details'
  get 'map' => 'map#index', as: 'map'

  get 'home' => 'blog#home', as: 'home'
  get 'rules' => 'blog#rules', as: 'rules'
  get 'faq' => 'blog#faq', as: 'faq'

  get 'accommodations' => 'accommodations#index', as: 'accommodations'
  get 'accommodations/:id' => 'accommodations#show', as: 'accommodation'
  patch 'accommodations/:id' => 'accommodations#update'

  post 'quantity/:accommodation_id' => 'reservations#quantity', as: 'quantity'
  post 'confirmation/:accommodation_id' => 'reservations#confirmation', as: 'confirmation'
  get 'reservations/:id' => 'reservations#show', as: 'edit_reservation'
  patch 'reservations/:id' => 'reservations#add_note', as: 'reservation_note'
  put 'reservations/:id/cancel' => 'reservations#cancel'
  get 'reservations' => 'reservations#index', as: 'admin_reservations'
  get 'reservations/:id/payment' => 'reservations#payment', as: 'admin_reservation_payment'
  delete 'reservations/:id' => 'reservations#delete', as: 'admin_reservation_delete'
  patch 'reservations/:id/paid' => 'reservations#paid', as: 'admin_reservation_paid'

  get 'users/new', as: 'signup'
  post 'users' => 'users#create'

  get    'login'   => 'sessions#new', as: 'login'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy', as: 'logout'

  get 'admin/index', as: 'admin'

  get 'admin/posts/home' => 'posts#show_home', as: 'admin_home'
  get 'admin/posts/rules' => 'posts#show_rule', as: 'admin_rule'
  get 'admin/posts/faq' => 'posts#show_faq', as: 'admin_faq'

  get 'admin/posts/home/new' => 'posts#new_home', as: 'new_home'
  get 'admin/posts/rules/new' => 'posts#new_rule', as: 'new_rule'
  get 'admin/posts/faq/new' => 'posts#new_faq', as: 'new_faq'

  post 'admin/posts' => 'posts#create', as: 'posts'

  get 'admin/posts/:id' => 'posts#show', as: 'edit_post'
  patch 'admin/posts/:id' => 'posts#update', as: 'post'
  patch 'admin/posts/:id/up' => 'posts#display_up', as: 'post_up'
  patch 'admin/posts/:id/down' => 'posts#display_down', as: 'post_down'
  delete 'admin/posts/:id' => 'posts#delete', as: 'delete_post'

  get 'admin/registrations' => 'registrations#index', as: 'registrations'
  get 'users/:id' => 'users#show', as: 'user'
  get 'users/:id/reservations' => 'users#reservations', as: 'user_reservations'
  patch 'users/:id' => 'users#update'
  patch 'users/:id/tier_approved' => 'users#tier_approved', as: 'tier_approved'

  get 'admin/buildings' => 'buildings#index', as: 'buildings'
  get 'admin/buildings/:id' => 'buildings#show', as: 'building'
  patch 'admin/buildings/:id' => 'buildings#update'

  get 'tiers' => 'tiers#index'
  get 'tiers/:id' => 'tiers#show', as: 'tier_edit'
  patch'tiers/:id' => 'tiers#update', as: 'tier'
  patch 'tiers/:id/tier_open_confirmation' => 'tiers#tier_open_email_confirm', as: 'tier_open_confirm'
  patch 'tiers/:id/send_open_confirmation' => 'tiers#tier_open_email_send', as: 'tier_open_send'
  get 'tiers/:id/email_logs' => 'email_logs#tier_email_logs', as: 'tier_email_logs'

  get 'instants' => 'instants#index'
  get 'instants/:id' => 'instants#show', as: 'instant_edit'
  patch'instants/:id' => 'instants#update', as: 'instant_update'
end

app/views/layouts/_error_messages.html.erb
<% if @error.errors.any? %>
  <di class="row">
    <div class="col-12">
      <div id="error_explanation">
        <div class="alert alert-danger">
          The form contains <%= pluralize(@error.errors.count, "error") %>.
        </div>
        <ul>
          <% @error.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </di>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, msg| %>
  <% unless key == :timedout %>
    <%= content_tag :div, class: "alert alert-dismissable alert-#{key}" do -%>
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
      </button>
      <%= msg %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_footer.html.erb
<div class="row footer justify-content-md-center">
  <div class="col-md-10">
    California Foundation for the Advancement of Electronic Arts &copy; <%= Time.new.year %> blah blah blah
  </div>
</div><!-- end footer row -->

app/views/layouts/_google_analytics.html.erb
<% if ENV['GOOGLE_ANALYTICS_UA'].present? %>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  // Enable 'Demographics and interest reports' in your analytics settings
  // ga('require', 'displayfeatures');

  // Enable 'Use enhanced link attribution' in your analytics settings
  // ga('require', 'linkid', 'linkid.js');

  ga('create', '<%= ENV["GOOGLE_ANALYTICS_UA"] %>', 'auto');
  ga('send', 'pageview');
</script>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light border rounded mb-3">
  <div class="container-fluid">
    <%= link_to 'FnF Cabins', home_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeaderContent" aria-controls="navbarHeaderContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarHeaderContent">
      <!-- Collect the nav links, forms, and other content for toggling -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active"><%= link_to 'rules', rules_path, class: 'nav-link' %></li>
          <li class="nav-item active"><%= link_to 'FAQ', faq_path, class: 'nav-link' %></li>
          <li class="nav-item active"><%= link_to 'book!', accommodations_path, class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false">cabin
              info</a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><%= link_to 'Saratoga Springs map', map_path, class: 'dropdown-item' %></li>
              <% if logged_in? %>
                <li><%= link_to 'cabin layout', details_path, class: 'dropdown-item' %></li>
              <% end %>
            </ul>
          </li>
          <% if logged_in? && is_admin? %>
            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false">admin</a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><%= link_to 'users', registrations_path, class: 'dropdown-item' %></li>
                <li><%= link_to 'reservations', admin_reservations_path, class: 'dropdown-item' %></li>
                <div class="dropdown-divider"></div>
                <li><%= link_to 'home posts', admin_home_path, class: 'dropdown-item' %></li>
                <li><%= link_to 'rule posts', admin_rule_path, class: 'dropdown-item' %></li>
                <li><%= link_to 'FAQ posts', admin_faq_path, class: 'dropdown-item' %></li>
                <div class="dropdown-divider"></div>
                <li><%= link_to 'buildings', buildings_path, class: 'dropdown-item' %></li>
                <li><%= link_to 'tiers', tiers_path, class: 'dropdown-item' %></li>
                <div class="dropdown-divider"></div>
                <li><%= link_to 'instants', instants_path, class: 'dropdown-item' %></li>
              </ul>
            </li>
          <% end %>
        </ul>

        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false">
              <%= logged_in? ? current_user.name : 'login' %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% if logged_in? %>
                <li><%= link_to 'profile', user_path(@current_user), class: 'dropdown-item' %></li>
                <li><%= link_to 'reservations', user_reservations_path(@current_user), class: 'dropdown-item' %></li>
                <li><%= link_to 'log out', logout_path, method: :delete, class: 'dropdown-item' %></li>
              <% else %>
                <li><%= link_to 'login', login_path, class: 'dropdown-item' %></li>
                <li><%= link_to 'register', signup_path, class: 'dropdown-item' %></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/_logo.html.erb
<div class="row mt-3">
  <div class="col ">
    <%= image_tag("goat-ball.jpg", class: "img-fluid mx-auto d-block") %>
  </div>
</div><!-- end logo row -->

app/views/layouts/_status.html.erb
<% if !user_reservation? %>
  <div class="row pt-3 mx-auto">
    <div class="col-10 offset-1 status alert-info">
      <% if !current_user.tier.nil? %>
        <% if current_user.tier.available <= DateTime.now %>
          <strong>You can book now!</strong>
          <div>You are approved and your tier's booking window has been opened, get on it!
            (select <%= link_to 'book!', accommodations_path %> above)
          </div>
        <% else %>
          <strong>Your tier has been assigned!</strong>
          <div>Your tier request has been processed and you will be able to book accommodations starting on
            <strong><%= current_user.tier.available.strftime("%a %-d %b %Y %T %Z") %></strong>. In the meantime, feel free to
              browse the lodgings, but you won't be able to reserve.</div>
        <% end %>
      <% else %>
        <strong>You are registered as a user and waiting on tier approval!</strong>
        <div>Your tier request has not yet been processed. Please contact
          <a href="mailto:cabins@fnf.org">cabins@fnf.org</a> if you think an error has occurred.
          In the meantime, feel free to browse the lodgings, but you won't be able to reserve until your tier opens up.
        </div>
      <% end %>
    </div>
  </div> <!-- end status row -->
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Cabins</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
  <link rel="apple-touch-icon" sizes="180x180" href="<%= image_url('apple-touch-icon.png') %>">
  <link rel="icon" type="image/png" sizes="32x32" href="<%= image_url('favicon-32x32.png') %>">
  <link rel="icon" type="image/png" sizes="16x16" href="<%= image_url('favicon-16x16.png') %>">

  <link rel="manifest" href="/site.webmanifest">
</head>
<body>
<div class="container">
  <%= render 'layouts/logo' %>
  <%= render 'layouts/header' %>
  <% if !flash.empty? %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %> mt-3" role="alert"><%= message %></div>
    <% end %>
  <% end %>

  <%= yield %>

  <%= render 'layouts/footer' %>
</div><!-- end container -->
<%= debug(params) if Rails.env.development? %>
</body>
</html>